version: '3'

services:
  db:
    container_name: ${DB_NAME}
    image: mongo:6
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    command: ['--auth']
  
  mongo-express: 
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${DB_NAME}
    ports:
      - 8081:8081
    restart: always
    
volumes:
  mongo-volume:
    external: false